In [8]:
import numpy as np
a=np.array([1,3,4,5,6,7])
print(a)
print(a[::-1])
print(a[3:4])

[1 3 4 5 6 7]
[7 6 5 4 3 1]
[5]


In [22]:
import numpy as np
a=np.array([[1,3,4,5,6],[3,5,9,0,8],[7,88,9,100,78]])
print( "Reversing the rows:\n",a[::-1])
print("Reversing the elements and rows:\n",a[::-1,::-1])
print("slicing the array:\n",a[:2,1:5:2])

Reversing the rows:
 [[  7  88   9 100  78]
 [  3   5   9   0   8]
 [  1   3   4   5   6]]
Reversing the elements and rows:
 [[ 78 100   9  88   7]
 [  8   0   9   5   3]
 [  6   5   4   3   1]]
slicing the array:
 [[3 5]
 [5 0]]


In [39]:
import numpy as np
a=np.array([[[1,2,3,4],[5,7,6,8],[4,6,8,9]],[[99,0,8,7],[33,45,32,1],[90,100,23,45]]])
print(a)
l=[]
print("revesing 2d arrays:\n",a[::-1])
print("reversing rows in 2d arrays:\n",a[::-1,::-1])
print("reversing elements&rows in 2d arrays:\n",a[::-1,::-1,::-1])
print("totally reversed:")
for  i in a:
    l.append(i[::-1,::-1])
print(np.array(l))
print("array slicing:\n",a[:1,:1,::-1])

[[[  1   2   3   4]
  [  5   7   6   8]
  [  4   6   8   9]]

 [[ 99   0   8   7]
  [ 33  45  32   1]
  [ 90 100  23  45]]]
revesing 2d arrays:
 [[[ 99   0   8   7]
  [ 33  45  32   1]
  [ 90 100  23  45]]

 [[  1   2   3   4]
  [  5   7   6   8]
  [  4   6   8   9]]]
reversing rows in 2d arrays:
 [[[ 90 100  23  45]
  [ 33  45  32   1]
  [ 99   0   8   7]]

 [[  4   6   8   9]
  [  5   7   6   8]
  [  1   2   3   4]]]
reversing elements&rows in 2d arrays:
 [[[ 45  23 100  90]
  [  1  32  45  33]
  [  7   8   0  99]]

 [[  9   8   6   4]
  [  8   6   7   5]
  [  4   3   2   1]]]
totally reversed:
[[[  9   8   6   4]
  [  8   6   7   5]
  [  4   3   2   1]]

 [[ 45  23 100  90]
  [  1  32  45  33]
  [  7   8   0  99]]]
array slicing:
 [[[4 3 2 1]]]


In [46]:
import numpy as np
a=np.array([1,2,3,4],dtype='S')
print(a)
b=np.array([1,2,3,4],dtype='U')
print(b)

[b'1' b'2' b'3' b'4']
['1' '2' '3' '4']


In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[2,3,4]])
print(a.shape)
x=a.reshape(1,6)
print(a.reshape(-1))
print(x)
print(a.reshape(3,2))

(2, 3)
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [26]:
import numpy as np
a=np.array([1,2,3,4,5,6])
for i in a:
    print(i,end =" ")
print("\n")
b=np.array([[1,2,3,4,5,6],[6,7,8,9,0,77]])
for i in b:
    print(i,end=" ")
    for j in i:
        print(j,end=" ")
    print("\n")
print("\n")
for i in np.nditer(b):
    print(i,end=" ")
print("\n")
c=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[88,99,0]]])
for i in np.nditer(c):
    print(i,end=" ")
        

1 2 3 4 5 6 

[1 2 3 4 5 6] 1 2 3 4 5 6 

[ 6  7  8  9  0 77] 6 7 8 9 0 77 



1 2 3 4 5 6 6 7 8 9 0 77 

1 2 3 4 5 6 4 5 6 88 99 0 

In [39]:
import numpy as np
a=np.array([[1,2,3],[9,0,8]])
b=np.array([[4,9,90],[4,3,21]])
c=np.add(a,b)
print("addition of a and b:\n",c)
d=np.array([1,2,3])
e=np.array([9,9])
#print(np.add(d,e))
print("addtion of e and d:")
for i,j in zip(d,e):
    print(i+j,end=" ")
print("\nZip Method return like this:",list(zip(d,e)))

    

addition of a and b:
 [[ 5 11 93]
 [13  3 29]]
addtion of e and d:
10 11 
Zip Method return like this: [(1, 9), (2, 9)]
2


In [56]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
c=np.subtract(a,b)
print("subtraction:",np.subtract(a,b))
print("multiplication :",np.multiply(a,b))
print("Division:",np.divide(b,a))
print("Power:",np.power(a,b))
print("mod:",np.mod(b,a))
print("abs:",np.abs(a,b))
print("quotient or mod:",np.divmod(a,b))
print("FOR 2DIM")
a=np.array([[1,2,3,4],[4,5,6,7]])
b=np.array([[6,7,8,9],[0,88,9,6]])
c=np.subtract(a,b)
print("subtraction:",np.subtract(a,b))
print("multiplication :",np.multiply(a,b))
print("Division:",np.divide(b,a))
print("Power:",np.power(a,b))
print("mod:",np.mod(b,a))
print("abs:",np.abs(a,b))
print("quotient or mod:",np.divmod(a,b))

subtraction: [-5 -5 -5 -5]
multiplication : [ 6 14 24 36]
Division: [6.         3.5        2.66666667 2.25      ]
Power: [     1    128   6561 262144]
mod: [0 1 2 1]
abs: [1 2 3 4]
quotient or mod: (array([1, 1, 1, 1], dtype=int32), array([0, 0, 0, 0], dtype=int32))
FOR 2DIM
subtraction: [[ -5  -5  -5  -5]
 [  4 -83  -3   1]]
multiplication : [[  6  14  24  36]
 [  0 440  54  42]]
Division: [[ 6.          3.5         2.66666667  2.25      ]
 [ 0.         17.6         1.5         0.85714286]]
Power: [[        1       128      6561    262144]
 [        1 591228065  10077696    117649]]
mod: [[0 1 2 1]
 [0 3 3 6]]
abs: [[1 2 3 4]
 [4 5 6 7]]
quotient or mod: (array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32), array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32))


In [62]:
import numpy as np
a=np.array([3.88,-2.33,-55.55,7.8])
print("Truncating:",np.trunc(a))
print("Around:",np.around(a))
print("Ceiling:",np.ceil(a))
print("Flooring :",np.floor(a))
print("Fix",np.fix(a))

Truncating: [  3.  -2. -55.   7.]
Around: [  4.  -2. -56.   8.]
Ceiling: [  4.  -2. -55.   8.]
Flooring : [  3.  -3. -56.   7.]
Fix [  3.  -2. -55.   7.]
