<a href="https://colab.research.google.com/github/Mahendravusa002/python-for-datascience/blob/main/numppy_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating np array by list

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


creating np array with tuple

In [ ]:
import numpy as np
b=np.array(((1,2,3),(4,5,6)))
print(b)
print(type(b))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


o

creating 0 dim array

In [10]:
c=np.array(9,dtype=float)
print(c)
print(c.dtype)
print(c.ndim)
d=np.array(66)
print(d)
e=np.array("m")
print()


9.0
float64
0


In [15]:
a=np.array([1,2,3],ndmin=4)
print(a,"\n ",a.ndim)

[[[[1 2 3]]]] 
  4


In [20]:
a=np.array([[[1.8,2,3],[4,2,5]],[[3,2,1],[5,2,4]]])
print("type:",type(a))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

type: <class 'numpy.ndarray'>
[[[1.8 2.  3. ]
  [4.  2.  5. ]]

 [[3.  2.  1. ]
  [5.  2.  4. ]]]
(2, 2, 3)
12
3
float64


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
